config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => "questions#index"

  resources :questions, :except => [:edit, :update, :destroy] do
    resources :responses, :only => [:new, :create]
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :title, :presence => true
  validates :body, :presence => true
  validates :user_id, :presence => true

  has_many :responses
  belongs_to :user

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/response.rb
class Response < ActiveRecord::Base
  validates :body, :presence => true
  
  belongs_to :question
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def create
    @question = current_user.questions.new(question_params)
    @question.published = Time.now
    if @question.save
      flash[:notice] = "Your question was posted."
      redirect_to questions_path
    else
      render :new
    end
  end

private

  def question_params
    params.require(:question).permit(:title, :body, :image)
  end

end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController

  def new
    @question = Question.find(params[:question_id])
    @response = Response.new
  end

  def create
    @question = Question.find(params[:question_id])
    @response = @question.responses.new(response_params)
    @response.published = Time.now
    if @response.save
      flash[:notice] = "Your response is appreciated!"
      redirect_to question_path(@question)
    else
      render :new
    end
  end

private

  def response_params
    params.require(:response).permit(:body)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = "You've been logged in."
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:alert] = "There was a problem logging you in."
      redirect_to log_in_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have been logged out successfully"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # This will show the signup confirmation email in development:
      # UserMailer.signup_confirmation(@user).deliver_now
      flash[:notice] = "Your account has been successfully created, " + @user.username
      redirect_to log_in_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
    render :edit
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "Your account has been successfully updated, " + @user.username
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :avatar)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Someone made a boo boo, papi!</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QStack</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <section class="container">
    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <div data-alert class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert"><%= msg %></div>
      <% end %>
    <% end %>
  </section>

  <nav class="container">
    <div id="user_nav">
      <%  if user_signed_in? %>
        Logged in as <%= current_user.email %>.
        <%= link_to "Edit Profile", edit_user_registration_path %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Sign Up", new_user_registration_path %> |
        <%= link_to "Login", new_user_session_path %>
      <% end %>
    </div>
  </nav>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/questions/_form.html.erb
<%= render 'layouts/errors', :object => @question %>

<%= form_for @question do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :body %>
  <%= f.text_area :body %>
  <%= f.label :image %>
  <%= f.file_field :image %>
  <%= f.submit "Ask" %>
<% end %>

app/views/questions/index.html.erb
<h1>List of Questions</h1>

<ul>
  <% @questions.each do |q| %>
  <li><%= link_to q.title, question_path(q) %></li>
  <% end %>
</ul>

<% if current_user %>
<p><%= link_to "Ask a question", new_question_path %></p>
<% else %>
<p>You must be logged in to ask a question or submit a response.</p>
<% end %>

app/views/questions/new.html.erb
<h1>Ask your question:</h1>

<%= render 'form' %>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>

<p><%= @question.body %></p>
<% if !@question.image_file_name %>
  <%= image_tag @question.image.url(:medium) %>
<% end %>

<h2>Responses</h2>

<% @question.responses.each do |r| %>
<div><%= r.body %></div>
<hr>
<% end %>

<% if current_user %>
<p><%= link_to "Submit a response", new_question_response_path(@question) %></p>
<% else %>
<p>You must be logged in to ask a question or submit a response.</p>
<% end %>

<p><%= link_to "Back", questions_path %></p>

app/views/responses/_form.html.erb
<%= render 'layouts/errors', :object => @response %>

<%= form_for [@question, @response] do |f| %>
  <%= f.label :body %>
  <%= f.text_area :body %>
  <%= f.submit "Respond" %>
<% end %>

app/views/responses/new.html.erb
<h1>You Got an Answer, hey?</h1>

<%= render 'form' %>

app/views/users/_form.html.erb
<%= render "layouts/errors", :object => @user %>

<%= form_for @user, :html =>{ :multipart => true, :class => "form-horizontal" } do |f| %>
  <div class="form-group">
    <%= f.label :username, :class => "col-md-2 control-label" %>
    <div class="col-md-10">
      <%= f.text_field :username %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, :class => "col-md-2 control-label" %>
    <div class="col-md-10">
      <%= f.text_field :email %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password, :class => "col-md-2 control-label" %>
    <div class="col-md-10">
      <%= f.password_field :password %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, :class => "col-md-2 control-label" %>
    <div class="col-md-10">
      <%= f.password_field :password_confirmation %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :avatar, :class => "col-md-2 control-label" %>
    <div class="col-md-10">
      <%= f.file_field :avatar, :class => "btn btn-default" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-md-10 col-md-offset-2">
      <%= f.submit :class => "btn btn-success" %>
      <%= link_to "Cancel", :back, :class => "btn btn-warning" %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit your account</h1>

<%= render "form" %>

app/views/users/new.html.erb
<h1>Create an account</h1>

<%= render "form" %>

app/views/users/show.html.erb
<h1>Welcome, <%= @user.username %>!</h1>

<%= image_tag @user.avatar.url(:thumb) %>

<p><%= link_to "Edit your account information", edit_user_path %>

<p><%= link_to "Ask a question",  new_question_path %></p>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Your questions</h3>
  </div>
  <div class="panel-body">
    <dl>
      <% @user.questions.each do |q|  %>
        <dt><%= link_to q.title, question_path(q) %></dt>
        <dd><time datetime="<%= q.published.strftime('%Y-%m-%dT%H:%M%z') %>"><%= q.published.strftime("Published on %B %d, %Y at %I:%M%P \(%Z\)") %></time></dd>
      <% end %>
    </dl>
  </div>
</div>
<!-- Low-Priority Feature
<p>Your responses:</p>
  <ul>
    <%# @user.responses.each do |r|  %>
      <li><%# link_to "response", question_path(r.question_id) %></li>
    <%# end %>
  </ul>
-->